### ISSUE TITLE
Integration tests

### ISSUE THREAD

**Issue by fntlnz** [iovisor/kubectl-trace#25]
kubectl trace is operating against kubernetes APIs to run bpftrace programs.
In order to verify the correctness of such integration and provide a stable experience to our users we need to write integration tests.

Tasks to consider this issue closed (can be done in multiple PRs):

- [x] Implement an integration testing framework (done in #26)
- [x] Integrate with travis  (done in #26)
- [x] Integration tests for run  (done in #26)
- [ ] Integration tests for run with attach
- [ ] Integration tests for get
- [ ] Integration tests for attach
- [ ] Integration tests for logs
